### ISSUE TITLE
The version 0.8.0 crashes after startup.

### ISSUE THREAD

**Issue by markflaisz** [detarkende/stremio-ncore-addon#52]
Hy detarkende.
I created a completely new environment and performed the installation there. The compose file has been copied as per your instructions. 

[](https://github.com/detarkende/stremio-ncore-addon/blob/master/docs/installation-guides/beginners/local-only.md)
```
name: stremio-ncore-addon
services:
  stremio-ncore-addon:
    environment:
      - NCORE_USERNAME=
      - NCORE_PASSWORD=
    image: detarkende/stremio-ncore-addon:0.8.0
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3443
        published: 3443
        protocol: tcp
      - target: 42069
        published: 42069
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/stremio-ncore-addon
        target: /addon
x-casaos:
  icon: https://github.com/detarkende/stremio-ncore-addon/blob/master/client/public/stremio-ncore-addon-logo-rounded.png?raw=true
  scheme: https
  title:
    custom: Stremio nCore addon
```
So: On the [*-*-*-*.local-ip.medicmobile.org](url) address, none of the ports (3443,443) respond, and the addon stops immediately. The only port I can access the settings interface is the HTTP port after a restart. 
Log:
```
stremio-ncore-addon-1  | Node.js v20.16.0
stremio-ncore-addon-1  | Environment variables parsed and loaded successfully.
stremio-ncore-addon-1  | Looking for torrent files...
stremio-ncore-addon-1  | Found 0 torrent files.
stremio-ncore-addon-1  | Missing config in config service. Cannot schedule deleteAfterHitnrun cron.
stremio-ncore-addon-1  | HTTP server started on port 3000!
stremio-ncore-addon-1  | Fetching local-ip keys
stremio-ncore-addon-1  | Torrent files loaded and verified.
stremio-ncore-addon-1  | node:internal/deps/undici/undici:13178
stremio-ncore-addon-1  |       Error.captureStackTrace(err);
stremio-ncore-addon-1  |             ^
stremio-ncore-addon-1  | 
stremio-ncore-addon-1  | TypeError: fetch failed
stremio-ncore-addon-1  |     at node:internal/deps/undici/undici:13178:13
stremio-ncore-addon-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
stremio-ncore-addon-1  |     at async fetchLocalIpKeys (file:///app/dist/server/utils/server-options.js:13:17)
stremio-ncore-addon-1  |     at async createServerOptions (file:///app/dist/server/utils/server-options.js:23:26)
stremio-ncore-addon-1  |     at async file:///app/dist/server/index.js:113:20 {
stremio-ncore-addon-1  |   [cause]: Error: getaddrinfo EAI_AGAIN local-ip.medicmobile.org
stremio-ncore-addon-1  |       at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
stremio-ncore-addon-1  |     errno: -3001,
stremio-ncore-addon-1  |     code: 'EAI_AGAIN',
stremio-ncore-addon-1  |     syscall: 'getaddrinfo',
stremio-ncore-addon-1  |     hostname: 'local-ip.medicmobile.org'
stremio-ncore-addon-1  |   }
stremio-ncore-addon-1  | }
stremio-ncore-addon-1  | 
```
