### ISSUE TITLE
Seeking doesn't work on Tizen OS

### ISSUE THREAD

**Issue by bytecraft32** [detarkende/stremio-ncore-addon#53]
On Tizen OS (Samsung Smart TV), seeking functionality doesn't work. I suspect the device expects specific HTTP headers or response formats for seeking support. The same functionality works correctly on WebOS, Stremio local Linux app, and Android devices.

I tested across multiple versions (0.8.0, 0.8.0-pre-release-2, 0.7.0, 0.6.0). 
Seeking works correctly with the Torrentio and Piratebay+ add-ons, which may be useful information when diagnosing this issue.

**Comment by detarkende** [comment]
Hi @bytecraft32 

Have you tried different torrents? 

I also have a Samsung Tizen OS Tv and seeking seems to work for me. Maybe it's specific to a torrent?

**Comment by markflaisz** [comment]
It didn’t work for me either, so I bought an Android TV box. Until the latest update (Tizen OS update in early March), it crashed every time I tried to start a video. Now it plays the video, but seeking doesn’t work. I thought this was a bug with the TV.

**Comment by bytecraft32** [comment]
At the moment, I'm investigating further to pinpoint the issue. It's possible I've misconfigured something.

I discovered that when using cloudflared, the seeking functionality works correctly on both my Tizen OS monitor and Tizen OS TV. However, when the setup is configured to be accessible only on the local network, the previously mentioned seeking issue occurs.

https://192-168-0-80.local-ip.medicmobile.org:3443/settings
 * Only accessible on local network 
Local network IP: 192.168.0.80

casaOs compose file:
```
name: stremio-ncore-addon
services:
  stremio-ncore-addon:
    cpu_shares: 90
    command: []
    deploy:
      resources:
        limits:
          memory: 7334M
    environment:
      - NCORE_PASSWORD=---------------------
      - NCORE_USERNAME=---------------------
    image: detarkende/stremio-ncore-addon:0.8.0
    labels:
      icon: https://github.com/detarkende/stremio-ncore-addon/blob/master/client/public/stremio-ncore-addon-logo-rounded.png?raw=true
    ports:
      - target: 3000
        published: "3000"
        protocol: tcp
      - target: 3443
        published: "3443"
        protocol: tcp
      - target: 42069
        published: "42069"
        protocol: ""
      - target: 443
        published: "443"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /home/server/Stremio
        target: /addon
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
    container_name: ""
    hostname: ""
x-casaos:
  author: self
  category: self
  hostname: 192-168-0-80.local-ip.medicmobile.org
  icon: https://github.com/detarkende/stremio-ncore-addon/blob/master/client/public/stremio-ncore-addon-logo-rounded.png?raw=true
  index: /
  is_uncontrolled: false
  port_map: ""
  scheme: https
  store_app_id: stremio-ncore-addon
  title:
    custom: Stremio nCore addon
```
